message
üß™ –§—É–Ω–∫—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–µ —Ç–µ—Å—Ç—ã
------------------------------
‚ùå –ù–µ–∫–æ—Ç–æ—Ä—ã–µ —Ñ—É–Ω–∫—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–µ —Ç–µ—Å—Ç—ã –Ω–µ –ø—Ä–æ–π–¥–µ–Ω—ã:
""
============================= test session starts =============================
"platform win32 -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0"
rootdir: C:\Users\mira1\OneDrive\–î–æ–∫—É–º–µ–Ω—Ç—ã\–ü–æ–ª–∏—Ç–µ—Ö\3 –∫—É—Ä—Å\6 —Å–µ–º–µ—Å—Ç—Ä\–ü—Ä–∞–∫—Ç–∏–∫–∞\recom_sys_checker
collected 11 items
""
logic\tests\collaborative_tests.py ...FFF..s.s
""
================================== FAILURES ===================================
___________________ test_fit_and_recommend_on_generated[1] ____________________
""
"task_info = {'algorithm': 'ALS', 'dataset': 'movie_ratings.csv', 'filter_type': 'user_based', 'k': 5, ...}"
k = 1
""
"    @pytest.mark.parametrize(""k"", [1, 2, 3])"
"    def test_fit_and_recommend_on_generated(task_info, k):"
        solution = load_solution_module()
        generated_dataset = get_dummy_data()
    
        solution.fit(generated_dataset)
"        user_id = generated_dataset[""user_id""].iloc[0]"
"        recs = solution.recommend(user_id, k=k)"
"        assert isinstance(recs, list)"
">       assert all(isinstance(i, int) for i in recs)"
E       assert False
E        +  where False = all(<generator object test_fit_and_recommend_on_generated.<locals>.<genexpr> at 0x00000208F2C2B760>)
""
logic\tests\collaborative_tests.py:78: AssertionError
___________________ test_fit_and_recommend_on_generated[2] ____________________
""
"task_info = {'algorithm': 'ALS', 'dataset': 'movie_ratings.csv', 'filter_type': 'user_based', 'k': 5, ...}"
k = 2
""
"    @pytest.mark.parametrize(""k"", [1, 2, 3])"
"    def test_fit_and_recommend_on_generated(task_info, k):"
        solution = load_solution_module()
        generated_dataset = get_dummy_data()
    
        solution.fit(generated_dataset)
"        user_id = generated_dataset[""user_id""].iloc[0]"
"        recs = solution.recommend(user_id, k=k)"
"        assert isinstance(recs, list)"
">       assert all(isinstance(i, int) for i in recs)"
E       assert False
E        +  where False = all(<generator object test_fit_and_recommend_on_generated.<locals>.<genexpr> at 0x00000208F2CC0900>)
""
logic\tests\collaborative_tests.py:78: AssertionError
___________________ test_fit_and_recommend_on_generated[3] ____________________
""
"task_info = {'algorithm': 'ALS', 'dataset': 'movie_ratings.csv', 'filter_type': 'user_based', 'k': 5, ...}"
k = 3
""
"    @pytest.mark.parametrize(""k"", [1, 2, 3])"
"    def test_fit_and_recommend_on_generated(task_info, k):"
        solution = load_solution_module()
        generated_dataset = get_dummy_data()
    
        solution.fit(generated_dataset)
"        user_id = generated_dataset[""user_id""].iloc[0]"
"        recs = solution.recommend(user_id, k=k)"
"        assert isinstance(recs, list)"
">       assert all(isinstance(i, int) for i in recs)"
E       assert False
E        +  where False = all(<generator object test_fit_and_recommend_on_generated.<locals>.<genexpr> at 0x00000208F2CC1620>)
""
logic\tests\collaborative_tests.py:78: AssertionError
=========================== short test summary info ===========================
FAILED logic/tests/collaborative_tests.py::test_fit_and_recommend_on_generated[1]
FAILED logic/tests/collaborative_tests.py::test_fit_and_recommend_on_generated[2]
FAILED logic/tests/collaborative_tests.py::test_fit_and_recommend_on_generated[3]
"=================== 3 failed, 6 passed, 2 skipped in 1.36s ===================="
""
""
""
""
üé® –°—Ç–∏–ª—å –∫–æ–¥–∞ (flake8)
------------------------------
‚ùå flake8: –ù–∞–π–¥–µ–Ω—ã –ø—Ä–æ–±–ª–µ–º—ã —Å–æ —Å—Ç–∏–ª–µ–º:
solution.py:0:1: E902 FileNotFoundError: [Errno 2] No such file or directory: 'solution.py'
""
""
üß± –§–æ—Ä–º–∞—Ç–∏—Ä–æ–≤–∞–Ω–∏–µ –∫–æ–¥–∞ (black)
------------------------------
‚ùå black: –§–æ—Ä–º–∞—Ç–∏—Ä–æ–≤–∞–Ω–∏–µ –æ—Ç–ª–∏—á–∞–µ—Ç—Å—è –æ—Ç —Å—Ç–∞–Ω–¥–∞—Ä—Ç–∞ black.
""
üìã –ü–æ–¥—Ä–æ–±–Ω–æ—Å—Ç–∏:
