message
üß™ –§—É–Ω–∫—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–µ —Ç–µ—Å—Ç—ã
------------------------------
‚ùå –ù–µ–∫–æ—Ç–æ—Ä—ã–µ —Ñ—É–Ω–∫—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–µ —Ç–µ—Å—Ç—ã –Ω–µ –ø—Ä–æ–π–¥–µ–Ω—ã:
""
============================= test session starts =============================
"platform win32 -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0"
rootdir: C:\Users\mira1\OneDrive\–î–æ–∫—É–º–µ–Ω—Ç—ã\–ü–æ–ª–∏—Ç–µ—Ö\3 –∫—É—Ä—Å\6 —Å–µ–º–µ—Å—Ç—Ä\–ü—Ä–∞–∫—Ç–∏–∫–∞\recom_sys_checker
collected 11 items
""
logic\tests\collaborative_tests.py ...FFF..sFs
""
================================== FAILURES ===================================
___________________ test_fit_and_recommend_on_generated[1] ____________________
""
"task_info = {'algorithm': 'SVD', 'dataset': 'movie_ratings.csv', 'filter_type': 'user_based', 'k': 10, ...}"
k = 1
""
"    @pytest.mark.parametrize(""k"", [1, 2, 3])"
"    def test_fit_and_recommend_on_generated(task_info, k):"
        solution = load_solution_module()
        generated_dataset = get_dummy_data()
    
        solution.fit(generated_dataset)
"        user_id = generated_dataset[""user_id""].iloc[0]"
"        recs = solution.recommend(user_id, k=k)"
"        assert isinstance(recs, list)"
">       assert all(isinstance(i, int) for i in recs)"
E       assert False
E        +  where False = all(<generator object test_fit_and_recommend_on_generated.<locals>.<genexpr> at 0x0000026572FCB680>)
""
logic\tests\collaborative_tests.py:78: AssertionError
___________________ test_fit_and_recommend_on_generated[2] ____________________
""
"task_info = {'algorithm': 'SVD', 'dataset': 'movie_ratings.csv', 'filter_type': 'user_based', 'k': 10, ...}"
k = 2
""
"    @pytest.mark.parametrize(""k"", [1, 2, 3])"
"    def test_fit_and_recommend_on_generated(task_info, k):"
        solution = load_solution_module()
        generated_dataset = get_dummy_data()
    
        solution.fit(generated_dataset)
"        user_id = generated_dataset[""user_id""].iloc[0]"
"        recs = solution.recommend(user_id, k=k)"
"        assert isinstance(recs, list)"
">       assert all(isinstance(i, int) for i in recs)"
E       assert False
E        +  where False = all(<generator object test_fit_and_recommend_on_generated.<locals>.<genexpr> at 0x0000026573060820>)
""
logic\tests\collaborative_tests.py:78: AssertionError
___________________ test_fit_and_recommend_on_generated[3] ____________________
""
"task_info = {'algorithm': 'SVD', 'dataset': 'movie_ratings.csv', 'filter_type': 'user_based', 'k': 10, ...}"
k = 3
""
"    @pytest.mark.parametrize(""k"", [1, 2, 3])"
"    def test_fit_and_recommend_on_generated(task_info, k):"
        solution = load_solution_module()
        generated_dataset = get_dummy_data()
    
        solution.fit(generated_dataset)
"        user_id = generated_dataset[""user_id""].iloc[0]"
"        recs = solution.recommend(user_id, k=k)"
"        assert isinstance(recs, list)"
">       assert all(isinstance(i, int) for i in recs)"
E       assert False
E        +  where False = all(<generator object test_fit_and_recommend_on_generated.<locals>.<genexpr> at 0x0000026573061540>)
""
logic\tests\collaborative_tests.py:78: AssertionError
_____________________ test_evaluate_returns_correct_rmse ______________________
""
"task_info = {'algorithm': 'SVD', 'dataset': 'movie_ratings.csv', 'filter_type': 'user_based', 'k': 10, ...}"
""
    def test_evaluate_returns_correct_rmse(task_info):
"        if task_info[""metric""] != ""RMSE"":"
"            pytest.skip(""–ú–µ—Ç—Ä–∏–∫–∞ –≤ –∑–∞–¥–∞–Ω–∏–∏ –Ω–µ RMSE"")"
    
        solution = load_solution_module()
        dummy_data = get_dummy_data(seed=42)
"        train = dummy_data.sample(frac=0.7, random_state=42)"
        test = dummy_data.drop(train.index)
        solution.fit(train)
    
        # –í—ã—á–∏—Å–ª–µ–Ω–∏–µ –æ–∂–∏–¥–∞–µ–º–æ–≥–æ RMSE (–µ—Å–ª–∏ –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –∫–∞–∫ baseline)
"        merged = pd.merge(test, train, on=[""user_id"", ""item""], suffixes=(""_test"", ""_train""))"
        if not merged.empty:
"            expected_rmse = np.sqrt(mean_squared_error(merged[""rating_test""], merged[""rating_train""]))"
        else:
            expected_rmse = 0.0
    
>       user_score = solution.evaluate(test)
                     ^^^^^^^^^^^^^^^^^^^^^^^
""
logic\tests\collaborative_tests.py:176: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
""
test_data =      user_id  item  rating
1          1   100       5
2          1   108       4
14         2   107       2
20        ...118       5
131       19   119       5
133       19   100       2
136       20   105       1
138       20   119       2
""
    def evaluate(test_data: pd.DataFrame) -> float:
"        """"""–û—Ü–µ–Ω–∏–≤–∞–µ—Ç –º–æ–¥–µ–ª—å –Ω–∞ —Ç–µ—Å—Ç–æ–≤–æ–π –≤—ã–±–æ—Ä–∫–µ –∏ –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç RMSE."""""""
        y_true = []
        y_pred = []
    
"        for _, row in test_data.iterrows():"
            user_id = row['user_id']
            item_id = row['item']
            true_rating = row['rating']
    
">           pred_rating = predict(user_id, item_id)"
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
E           TypeError: predict() missing 1 required positional argument: 'item_id'
""
solutions\solution.py:114: TypeError
=========================== short test summary info ===========================
FAILED logic/tests/collaborative_tests.py::test_fit_and_recommend_on_generated[1]
FAILED logic/tests/collaborative_tests.py::test_fit_and_recommend_on_generated[2]
FAILED logic/tests/collaborative_tests.py::test_fit_and_recommend_on_generated[3]
FAILED logic/tests/collaborative_tests.py::test_evaluate_returns_correct_rmse
"=================== 4 failed, 5 passed, 2 skipped in 1.35s ===================="
""
""
""
""
üé® –°—Ç–∏–ª—å –∫–æ–¥–∞ (flake8)
------------------------------
‚ùå flake8: –ù–∞–π–¥–µ–Ω—ã –ø—Ä–æ–±–ª–µ–º—ã —Å–æ —Å—Ç–∏–ª–µ–º:
"solution.py:10:1: E302 expected 2 blank lines, found 1"
solution.py:31:68: W291 trailing whitespace
solution.py:32:42: E128 continuation line under-indented for visual indent
solution.py:32:80: E501 line too long (82 > 79 characters)
solution.py:65:80: E501 line too long (80 > 79 characters)
"solution.py:103:1: E302 expected 2 blank lines, found 1"
"solution.py:121:1: E305 expected 2 blank lines after class or function definition, found 1"
solution.py:137:69: W292 no newline at end of file
""
""
üß± –§–æ—Ä–º–∞—Ç–∏—Ä–æ–≤–∞–Ω–∏–µ –∫–æ–¥–∞ (black)
------------------------------
‚ùå black: –§–æ—Ä–º–∞—Ç–∏—Ä–æ–≤–∞–Ω–∏–µ –æ—Ç–ª–∏—á–∞–µ—Ç—Å—è –æ—Ç —Å—Ç–∞–Ω–¥–∞—Ä—Ç–∞ black.
""
üìã –ü–æ–¥—Ä–æ–±–Ω–æ—Å—Ç–∏:
